### ISSUE TITLE
Add an 8.x branch

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message_subscribe#13]
I'm going to have some time in the upcoming weeks to start porting this module to 8.x. For ease of PR review, an 8.x branch would be nice.

Thanks!

**Comment by amitaibu** [comment]
> some time in the upcoming weeks to start porting this module to 8.x

That's great. There you go - https://github.com/Gizra/message_subscribe/tree/8.x-1.x 😄

**Comment by jhedstrom** [comment]
👍
