### ISSUE TITLE
Consider removing hooks and switching to an event dispatcher/subscriber model

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message_subscribe#17]
Some considerations:
- The hooks use a series of arrays, while an event dispatcher system sends out an `Event` object.
- We'd need to encapsulate the various array properties that the hooks use into something like an `SubscribersCollection` object that could be passed along with the `Event` object.

Other pros/cons?

**Comment by amitaibu** [comment]
Are you going to be on New-Orleans? We can discuss this in person! ;)

**Comment by jhedstrom** [comment]
@amitaibu I will be there indeed. See you there!
