### ISSUE TITLE
Alpha release to d.o.

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message_subscribe#24]
I think this and message notify are now ready for alpha releases on d.o. cc/ @amitaibu

**Comment by amitaibu** [comment]
Good idea, I'll try to push one in the next couple of days.

**Comment by amitaibu** [comment]
@jhedstrom You now have commit access on GitHub and d.o. to both projects. Care to cut an alpha? 😄

**Comment by jhedstrom** [comment]
@amitaibu I just saw this! Thanks! (I've been on vacation for the past 2 weeks.) I'll cut an alpha after #25 is completed!

**Comment by jhedstrom** [comment]
I'm going to cut an alpha release now.
