### ISSUE TITLE
Message subscribe email should unset email notifier

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message_subscribe#30]
Over in #28 I realized that when the default notifier is set to email, the message subscribe email module will still send emails for folks that have opted out.

In `message_subscribe_email_message_subscribe_get_subscribers_alter()`, the `email` notifier is only added, but never unset. Perhaps this is just a documentation issue that default notifiers should be empty if using this module?

**Comment by amitaibu** [comment]
> the message subscribe email module will still send emails for folks that have opted out.

That should be fixed then - it's a bug :)
