### ISSUE TITLE
Is there an existing way to prevent duplicate notifications for multiple subscriptions

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message_subscribe#69]
I'm a bit stumped on this one.

Say that a system is in place to allow term, and user subscriptions. All of these would be triggered via `hook_node_insert()`, since when subscribed to a user, notifications are with regards to new content by that user, and similar with term subscriptions.

Now, since these are 2 different subscriptions (flags), if a user is subscribed to `term a`, and `author 2`, when a node with `term a`, written by `author 2` is added, 2 calls to `Subscribers::sendMessage()` are made, with 2 different message templates (since there are different templates for the 2 types of subscription).

Assuming for performance that processing is done via the queue system, is there a way when those queues trigger to prevent the 2 notifications from being emailed about the same node?

**Comment by jhedstrom** [comment]
Ahah, perhaps this is what the `$context` is for?

```
   *   $context = array(
   *     'node' => array(1),
   *     // The node author.
   *     'user' => array(10),
   *     // Related taxonomy terms.
   *     'taxonomy_term' => array(100, 200, 300)
   *   );
```

This would presumably work, but would require standardizing on a single template for different types of subscriptions I think...

**Comment by amitaibu** [comment]
@jhedstrom do you mean, how to confirm a Message is not sent twice for the same node ID?

If that's the case, since you don't know at which point a message is going to be sent, the way I do it, is have a reference field to the nodes from the message. So, the query I will perform in the next queue batch is, or prior to actual sending will confirm it was not already sent.

**Comment by jhedstrom** [comment]
:+1: for the node reference field. I was able to achieve this by combining that technique with using more advanced `$context` arguments to the subscriber service (eg, instead of having 3 different templates for users, terms, and nodes, use a single template and populate the context array with the relevant entity types).
