### ISSUE TITLE
Introduce alter hook immediately before sending messages

### ISSUE THREAD

**Issue by jhedstrom** [Gizra/message_subscribe#79]
I'm working on a project where advanced knowledge of *why* a notification was sent is desired in the message template. When using advanced contexts, one of several different subscription flags can result in a user receiving a notification (eg, subscribed to a term and an author).

The solution I have in mind is to add a flag entity reference to the message, and since the subscribers array has the user's relevant flags in it, that could be attached to the message entity right before it is sent. 

In order to do this, a new alter hook will be needed in `Subscribers::send`:

```php
      $cloned_message = $message->createDuplicate();
      // Push a copy of the original message into the new one.
      $cloned_message->original = $message;
      // Set the owner to this user.
      $cloned_message->setOwnerId($uid);

      $values += ['notifiers' => []];

      // Send the message using the required notifiers.
      foreach (array_unique($values['notifiers']) as $notifier_name) {
        $options = !empty($notify_options[$notifier_name]) ? $notify_options[$notifier_name] : [];
        $options += [
          'save on fail' => FALSE,
          'save on success' => FALSE,
          'context' => $context,
        ];

        $this->messageNotifier->send($cloned_message, $options, $notifier_name);
```

I propose `hook_message_subscribe_message_alter(MessageInterface $message, $values)`, since `$values` contains the flag IDs for the given user. I would be called right before the notifiers are looped through.

**Comment by amitaibu** [comment]
How about when we fetch the subscribed UIDs we could add some metadata. This can actually become an object, something like:

`MessageSubscribeDeliveryCandidateInterface`

where you could `::getReason` that will return an array with the matching entities or other arbitrary reasons?

**Comment by amitaibu** [comment]
So then just before delivery implementing modules could alter stuff or even `::doNotSend` it

**Comment by jhedstrom** [comment]
So replace what's currently an array with this new object? Right now we have in the `$values` array in the `send()` method (for each uid):

```php
$values = [
  'flags' => [...],
  'notifiers' => [...],
];
```

**Comment by amitaibu** [comment]
I mean, we can stay with an array, it just feels a bit more D8 to turn it into an object that will hide some of the implementation details. Mostly depends if you have the motivation and time to tackle this ;)

**Comment by jhedstrom** [comment]
I've introduced an object, but arrays are still supported. In a follow-up, it would be good to use `trigger_error('...', E_USER_DEPRECATED)` when arrays are used. When that happens this module's own implementations will need to be updated to use the object rather than arrays.

**Comment by amitaibu** [comment]
Awesome! Why do you want to keep array support - don't you prefer to already deprecate it, given we're still in alpha?

**Comment by jhedstrom** [comment]
I was thinking I'd delay changing `message_digest`, but might as well do that bit now too. Since this is ready to go, I'll finish removal in #81.
